# simple dockerfile to test OCP s2i using Dockerfile 

FROM registry.access.redhat.com/ubi7:latest

# CMD ["/bin/bash", "-c", "sleep infinity"]

# Chaging Paramerts of the docker file to generate a new output in OCP pod. 

CMD ["/bin/bash", "-c", "--", "while true; do sleep 30; done;"]
